# Generated by Django 5.2.1 on 2025-05-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(choices=[(500, '500'), (1000, '1000'), (2500, '2500'), (5000, '5000')], default=500),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('g', 'Gram'), ('ml', 'Mililitre')], default='g', max_length=2),
        ),
    ]
